<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-09-12T14:05:36Z" name="Default Suite" finished-at="2018-09-12T14:05:40Z" duration-ms="3991">
    <groups>
      <group name="BuyTickets">
        <method signature="LotBiletyTTT.Test_BuyTicketsEU(java.lang.String, java.lang.String, java.lang.String, org.apache.poi.xssf.usermodel.XSSFCell, org.apache.poi.xssf.usermodel.XSSFCell)[pri:0, instance:LOT.LotBiletyTTT@41c2284a]" name="Test_BuyTicketsEU" class="LOT.LotBiletyTTT"/>
      </group> <!-- BuyTickets -->
    </groups>
    <test started-at="2018-09-12T14:05:36Z" name="LOTests" finished-at="2018-09-12T14:05:40Z" duration-ms="3991">
      <class name="LOT.LotBiletyTTT">
        <test-method is-config="true" signature="setUp()[pri:0, instance:LOT.LotBiletyTTT@41c2284a]" started-at="2018-09-12T14:05:36Z" name="setUp" finished-at="2018-09-12T14:05:39Z" duration-ms="2913" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="Test_BuyTicketsEU(java.lang.String, java.lang.String, java.lang.String, org.apache.poi.xssf.usermodel.XSSFCell, org.apache.poi.xssf.usermodel.XSSFCell)[pri:0, instance:LOT.LotBiletyTTT@41c2284a]" started-at="2018-09-12T14:05:39Z" name="Test_BuyTicketsEU" data-provider="dataEU" finished-at="2018-09-12T14:05:39Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NullPointerException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.NullPointerException
at DDT.ExcelDataConfig.getRowCount(ExcelDataConfig.java:47)
at LOT.LotBiletyTTT.passDataEU(LotBiletyTTT.java:227)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 21 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_BuyTicketsEU -->
        <test-method is-config="true" signature="tearDown2()[pri:0, instance:LOT.LotBiletyTTT@41c2284a]" started-at="2018-09-12T14:05:39Z" name="tearDown2" finished-at="2018-09-12T14:05:39Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown2 -->
        <test-method is-config="true" signature="tearDown1()[pri:0, instance:LOT.LotBiletyTTT@41c2284a]" started-at="2018-09-12T14:05:39Z" name="tearDown1" finished-at="2018-09-12T14:05:40Z" duration-ms="1045" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown1 -->
      </class> <!-- LOT.LotBiletyTTT -->
    </test> <!-- LOTests -->
  </suite> <!-- Default Suite -->
</testng-results>
